image: python:3.11

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - build
  - deploy

before_script:
  - pip install mkdocs mkdocs-material

build:
  stage: build
  script:
    - mkdocs build
  artifacts:
    paths:
      - site/

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - mv site public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
